### ISSUE TITLE
API documents

### ISSUE THREAD

**Issue by eried** [T-vK/Electric-Unicycle-Interface#6]
This is brilliant! I got an old msuper v2 wheel and since the apps are all dead I was thinking this opens a lot of possibilities for lights and such... may I ask if the protocol is documented somewhere? i.e. if there is a PC app doing this?

**Comment by T-vK** [comment]
I had to reverse engineer it, there is no documentation afaik.

**Comment by eried** [comment]
Oh, thanks for the answer. Just as a closing question, do you recommend madden or comfort to start 😅 i just got this old wheel

**Comment by T-vK** [comment]
It comes down to personal preference really. I never really liked the soft modes, so I prefer the hardest onse.

**Comment by eried** [comment]
Thanks again! I will continue dreaming what I can do with this :) ESP32 and RGB lights are probably a must for my old wheel...
